gingersnap-project/db-syncer

src/main/resources/application.properties, src/test/java/org/gingesnap/GreetingResourceIT.java
=> Disable dev services and IT test for now to prevent running extra

src/main/java/org/gingesnap/cdc/EngineWrapper.java, src/main/java/org/gingesnap/cdc/ManagedEngine.java, src/main/java/org/gingesnap/cdc/OffsetBackend.java, src/main/java/org/gingesnap/cdc/ReschedulingTask.java, src/main/java/org/gingesnap/cdc/cache/CacheService.java, src/main/java/org/gingesnap/cdc/cache/ErrorNotifier.java, src/main/java/org/gingesnap/cdc/cache/hotrod/HotRodCacheBackend.java, src/main/java/org/gingesnap/cdc/cache/hotrod/HotRodOffsetBackend.java, src/main/java/org/gingesnap/cdc/cache/hotrod/HotRodService.java, src/main/java/org/gingesnap/cdc/configuration/Connector.java, src/main/java/org/gingesnap/cdc/consumer/BatchConsumer.java, src/main/java/org/gingesnap/cdc/remote/RemoteOffsetStore.java, src/main/java/org/gingesnap/cdc/remote/RemoteSchemaHistory.java, src/main/java/org/gingesnap/cdc/util/AggregateCompletionStage.java, src/main/java/org/gingesnap/cdc/util/CompletionStages.java, src/main/resources/application.properties
Retry connecting to the cache backend, restarting engine when ready Use name of service as topic
=> Stop engine and cache service upon backend error.

README.md, pom.xml, src/main/java/org/gingesnap/cdc/EngineWrapper.java, src/main/java/org/gingesnap/cdc/cache/hotrod/HotRodSchemaBackend.java, src/main/java/org/gingesnap/cdc/connector/DatabaseProvider.java, src/main/java/org/gingesnap/cdc/remote/RemoteSchemaHistory.java, src/main/resources/application.properties, src/main/resources/mssql/after.sh, src/main/resources/mssql/after.sql, src/main/resources/mssql/mssql.yml, src/main/resources/mssql/setup.sh, src/main/resources/mssql/setup.sql
The most basic setup I could get for SQL Server.
Most notably, I've moved the provider configuration to last, so it has a higher priority and can override values.
=> SQL Server setup

pom.xml, src/main/java/io/gingersnap_project/cdc/EngineWrapper.java, src/main/java/io/gingersnap_project/cdc/chain/CacheBackendLink.java, src/main/java/io/gingersnap_project/cdc/chain/Event.java, src/main/java/io/gingersnap_project/cdc/chain/EventContext.java, src/main/java/io/gingersnap_project/cdc/chain/EventFilterLink.java, src/main/java/io/gingersnap_project/cdc/chain/EventProcessingChain.java, src/main/java/io/gingersnap_project/cdc/chain/EventProcessingChainFactory.java, src/main/java/io/gingersnap_project/cdc/consumer/BatchConsumer.java, src/main/java/io/gingersnap_project/cdc/util/Serialization.java
Added a custom processing pipeline, where we can remove some dependencies (Groovy). Also directly parsing the Kafka event to our JSON object, so we can remove Jackson too, I think.
=> Custom processing pipeline

.github/workflows/pull_requests.yml, .github/workflows/test_report.yaml, src/main/resources/application.properties
Just a simple action, running the verify for JDK 17. For the future we should set up something using testcontainers or something similar.
=> Action to run in PRs

.gitmodules, pom.xml, src/test/java/io/gingersnapproject/proto/JSONMappingTest.java
Integration with gingersnap-api.
Added git submodule to https://github.com/gingersnap-project/api.git
Added mvn plugin for generation
=> added gingersnap-api integration

src/main/java/io/gingersnapproject/cdc/EngineWrapper.java, src/main/java/io/gingersnapproject/cdc/cache/CacheService.java, src/main/java/io/gingersnapproject/cdc/cache/hotrod/HotRodService.java
Using the configured rule name as the cache name. I'll update the cache-manager to use the rule name as well.
=> Use rule name as cache name

src/main/java/io/gingersnapproject/cdc/cache/hotrod/HotRodService.java, src/main/java/io/gingersnapproject/cdc/configuration/Rule.java, src/main/resources/application.properties
* Kept the PrependTranslators for now
=> Remove key prefix handler

src/main/java/io/gingersnapproject/cdc/ManagedEngine.java, src/main/java/io/gingersnapproject/cdc/cache/hotrod/HotRodService.java, src/main/java/io/gingersnapproject/cdc/configuration/Rule.java, src/main/resources/application.properties
- Make Rule KeyColumns configuration mandatory
- Utilise @PostConstruct to ensure HotRodService is initiated before use
@wburns @jabolina I originally just wanted to create a PR for the first commit, but I kept getting startup failures with the HotRodService hence the additional commit.
=> Make Rule KeyColumns configuration mandatory

pom.xml, src/main/java/io/gingersnapproject/cdc/EngineWrapper.java, src/main/java/io/gingersnapproject/cdc/cache/hotrod/HotRodCacheBackend.java, src/main/java/io/gingersnapproject/cdc/cache/hotrod/HotRodService.java, src/main/java/io/gingersnapproject/cdc/event/Events.java, src/main/java/io/gingersnapproject/cdc/event/NotificationManager.java, src/main/java/io/gingersnapproject/metrics/BaseStreamingBeanLookup.java, src/main/java/io/gingersnapproject/metrics/CacheServiceAccessRecord.java, src/main/java/io/gingersnapproject/metrics/DBSyncerMetrics.java, src/main/java/io/gingersnapproject/metrics/GenericStreamingBeanLookup.java, src/main/java/io/gingersnapproject/metrics/MySQLStreamingBeanLookup.java, src/main/java/io/gingersnapproject/metrics/micrometer/MicrometerMetrics.java, src/main/java/io/gingersnapproject/metrics/micrometer/MySQLMetrics.java, src/main/java/io/gingersnapproject/metrics/micrometer/StreamingMetrics.java, src/main/java/io/gingersnapproject/metrics/micrometer/TimerMetrics.java, src/test/java/io/gingersnapproject/metrics/MetricsResourceTest.java, src/test/java/io/gingersnapproject/testcontainers/BaseGingersnapResourceLifecycleManager.java
Not the best good-looking code but Debezium only exposes metrics via JMX. I'm getting the instances from `MBeanServer` to be able to invoke the methods.
=> Expose metrics from Debezium connector

src/main/java/io/gingersnapproject/metrics/micrometer/MicrometerMetrics.java, src/main/java/io/gingersnapproject/metrics/micrometer/MySQLMetrics.java, src/main/java/io/gingersnapproject/metrics/micrometer/StreamingMetrics.java, src/main/java/io/gingersnapproject/metrics/micrometer/TagUtil.java, src/main/java/io/gingersnapproject/metrics/micrometer/TimerMetrics.java, src/test/java/io/gingersnapproject/metrics/MetricsResourceTest.java, src/test/java/io/gingersnapproject/testcontainers/BaseGingersnapResourceLifecycleManager.java
=> Micrometer naming convention

pom.xml, src/main/java/io/gingersnapproject/k8s/CacheRuleInformer.java, src/test/java/io/gingersnapproject/k8s/ConfigMapEventHandlerTest.java, src/test/java/io/gingersnapproject/proto/JSONMappingTest.java
Adding test for ConfigMapEventhandler
=>  test for ConfigMapEventHandler

src/main/java/io/gingersnapproject/cdc/CacheBackend.java, src/main/java/io/gingersnapproject/cdc/EngineWrapper.java, src/main/java/io/gingersnapproject/cdc/ManagedEngine.java, src/main/java/io/gingersnapproject/cdc/OffsetBackend.java, src/main/java/io/gingersnapproject/cdc/cache/CacheService.java, src/main/java/io/gingersnapproject/cdc/cache/hotrod/HotRodCacheBackend.java, src/main/java/io/gingersnapproject/cdc/cache/hotrod/HotRodService.java, src/main/java/io/gingersnapproject/cdc/consumer/BatchConsumer.java, src/main/java/io/gingersnapproject/cdc/event/Events.java, src/main/java/io/gingersnapproject/cdc/event/NotificationManager.java, src/main/java/io/gingersnapproject/cdc/remote/RemoteOffsetStore.java
=> Using multiple backends and single service

pom.xml, src/main/java/io/gingersnapproject/cdc/EngineWrapper.java, src/main/java/io/gingersnapproject/cdc/ManagedEngine.java, src/main/java/io/gingersnapproject/cdc/chain/EventFilterLink.java, src/main/java/io/gingersnapproject/cdc/consumer/BatchConsumer.java, src/test/java/io/gingersnapproject/cdc/ManagedEngineTest.java, src/test/java/io/gingersnapproject/cdc/ReschedulingTaskTest.java, src/test/java/io/gingersnapproject/cdc/chain/EventProcessingChainTest.java, src/test/java/io/gingersnapproject/cdc/consumer/BatchConsumerTest.java, src/test/java/io/gingersnapproject/cdc/util/SerializationTest.java, src/test/java/io/gingersnapproject/fwk/ControlledCacheBackend.java, src/test/java/io/gingersnapproject/proto/JSONMappingTest.java, src/test/java/io/gingersnapproject/util/Utils.java
Adding some functional tests to some specific parts. I'll start doing some integrations, but as that will need the containers to be running, I am leaving it for later.
=> Adding some functional tests

pom.xml, src/main/java/io/gingersnapproject/metrics/micrometer/MicrometerMetrics.java, src/main/java/io/gingersnapproject/metrics/micrometer/MySQLMetrics.java, src/main/java/io/gingersnapproject/metrics/micrometer/StreamingMetrics.java, src/test/java/io/gingersnapproject/testcontainers/MySQLResources.java
Notes:
* removed duplicated dependency in pom.xml
* tried again to use tmpfs in MySQL container, using `.withTmpFs(Map.of("/var/lib/mysql", "rw"))` :crossed_fingers:
=> Unregister rule's metrics

src/main/java/io/gingersnapproject/cdc/CacheBackend.java, src/main/java/io/gingersnapproject/cdc/EngineWrapper.java, src/main/java/io/gingersnapproject/cdc/cache/CacheIdentifier.java, src/main/java/io/gingersnapproject/cdc/cache/CacheService.java, src/main/java/io/gingersnapproject/cdc/cache/hotrod/HotRodCacheBackend.java, src/main/java/io/gingersnapproject/cdc/cache/hotrod/HotRodService.java, src/main/java/io/gingersnapproject/cdc/remote/RemoteOffsetStore.java, src/main/java/io/gingersnapproject/cdc/remote/RemoteSchemaHistory.java, src/test/java/io/gingersnapproject/cdc/ManagedEngineTest.java, src/test/java/io/gingersnapproject/fwk/ControlledCacheBackend.java
Using the cache URI with the rule to identify the cache manager. This will help with the following PRs. We have only the single URI from the configuration, but that will change.
=> Use URI and rule to identify the cache

src/main/java/io/gingersnapproject/cdc/EngineWrapper.java, src/main/java/io/gingersnapproject/cdc/configuration/Database.java, src/main/resources/application.properties, src/test/java/io/gingersnapproject/cdc/ManagedEngineTest.java, src/test/java/io/gingersnapproject/testcontainers/BaseGingersnapResourceLifecycleManager.java
https://github.com/servicebinding/spec#well-known-secret-entries
=> Utilise 'username' instead of 'user' in configuration

src/main/java/io/gingersnapproject/metrics/BaseStreamingBeanLookup.java, src/main/java/io/gingersnapproject/metrics/micrometer/MicrometerMetrics.java, src/main/java/io/gingersnapproject/metrics/micrometer/MySQLMetrics.java, src/main/java/io/gingersnapproject/metrics/micrometer/StreamingMetrics.java, src/main/java/io/gingersnapproject/metrics/micrometer/TagUtil.java, src/test/java/io/gingersnapproject/metrics/MetricsResourceTest.java, src/test/java/io/gingersnapproject/testcontainers/Profiles.java
Expose more information about metrics to allow more complex filtering
Closes #72
=> Add connector type to Micrometer tags

src/main/java/io/gingersnapproject/metrics/OracleStreamingBeanLookup.java, src/main/java/io/gingersnapproject/metrics/micrometer/MetricUtil.java, src/main/java/io/gingersnapproject/metrics/micrometer/MicrometerMetrics.java, src/main/java/io/gingersnapproject/metrics/micrometer/OracleGaugeMetric.java, src/main/java/io/gingersnapproject/metrics/micrometer/OracleTimeGaugeMetric.java, src/test/java/io/gingersnapproject/metrics/MetricsResourceTest.java
=> Add metrics for Oracle Database Connector

src/main/java/io/gingersnapproject/cdc/consumer/BatchConsumer.java, src/main/java/io/gingersnapproject/cdc/translation/ColumnStringTranslator.java, src/test/java/io/gingersnapproject/cdc/MultiCacheManagerTest.java, src/test/java/io/gingersnapproject/cdc/PublishChangesTest.java, src/test/java/io/gingersnapproject/testcontainers/BaseContainerTest.java, src/test/java/io/gingersnapproject/testcontainers/BaseGingersnapResourceLifecycleManager.java, src/test/java/io/gingersnapproject/testcontainers/annotation/ContainerInject.java, src/test/java/io/gingersnapproject/testcontainers/database/Oracle.java, src/test/java/io/gingersnapproject/testcontainers/hotrod/CacheManagerContainer.java, src/test/java/io/gingersnapproject/testcontainers/hotrod/HotRodContainer.java, src/test/java/io/gingersnapproject/testcontainers/hotrod/InfinispanContainer.java, src/test/java/io/gingersnapproject/util/Utils.java, src/test/resources/postgres/setup.sql
* Adding a test to verify the CDC, that the event is applied in the remote cache;
* Additional verification in `MultiCacheManagerTest` when using Oracle.
=> Added complete CDC test
